#70
UniAuth/uniauth-backend pull request #104
Opened 2021-02-20 10:15 UTC by kdsinghcoder

Fixed issue: #70

2021-02-20 19:39 UTC, YashKumarVerma requested changes

2021-02-20 19:39 UTC, YashKumarVerma commented on src/account/account.service.spec.ts
>  import { AccountService } from './account.service';
remove the lines, no need to keep as comments.

2021-02-20 19:39 UTC, YashKumarVerma commented
also, fill the PR body & title properly.

2021-02-21 11:01 UTC, kdsinghcoder commented on src/account/account.service.spec.ts
>  import { AccountService } from './account.service';
Done

2021-02-24 19:17 UTC, YashKumarVerma requested changes
![https://i.imgur.com/c6TQ0sg.png](https://i.imgur.com/c6TQ0sg.png)

2021-02-25 19:41 UTC, closed without merging