logged in user list
UniAuth/uniauth-backend pull request #109
Opened 2021-02-22 07:03 UTC by tanay13

fixes #106 {Backend part}

2021-02-22 07:05 UTC, tanay13 commented
@YashKumarVerma Please review this

2021-02-22 07:25 UTC, YashKumarVerma approved these changes

2021-02-22 07:25 UTC, YashKumarVerma commented on src/user/user.service.ts
remove `any` datatype and put exact data type

2021-02-22 07:47 UTC, tanay13 commented on src/user/user.service.ts
Can you help me out with the data type i tried putting <code>Array<mongoose.Schema.Types.ObjectId></code>but this is also throwing some error?

2021-02-22 16:58 UTC, YashKumarVerma requested changes

2021-02-22 16:58 UTC, YashKumarVerma commented on src/dashboard/dashboard.controller.ts
> +  }
we're using subdocument, use .populate method to get user details

2021-02-22 17:55 UTC, tanay13 commented
@YashKumarVerma I made the changes, please have look

2021-02-23 03:36 UTC, YashKumarVerma requested changes
also, add screenshots of application when changes done

2021-02-23 03:36 UTC, YashKumarVerma commented on src/application/application.service.ts
> +
this is a valid step, but where are we selecting a single application here ?

we need to combine findOneById and .populate to get results in one query

2021-02-23 05:09 UTC, tanay13 commented on src/application/application.service.ts
> +
After changing the above code to this 

```js
  @Get('/details/:id')
  @UseGuards(JwtAuthGuard)
  async showUser(@Request() req, @Param('id') id: string) {
    const loggedInUser: LoggedInUser = req.user;
    const user = await this.applicationService.findOneById(id);
    const records = await user.populate('participants')
    console.log(records)

  }

```
I am getting this type of result

<img width="400" alt="test1" src="https://user-images.githubusercontent.com/61361310/108804403-2ed95680-75c3-11eb-8239-261512d23e11.PNG">

Do i have to loop through the <code>id</code> array to show the user's detail?

2021-02-24 10:11 UTC, tanay13 commented
<img width="464" alt="loginuserpart" src="https://user-images.githubusercontent.com/61361310/108984788-51986780-76b6-11eb-84d1-de29d71bed97.PNG">
@YashKumarVerma After the <code>forEach</code> loop when I am printing the array it is showing empty, why is this happening?

2021-02-24 13:13 UTC, YashKumarVerma requested changes
the code to display the user list should reside in the dashboard controller and call the service from application module.

I have made the changes required to successfully render the results. Kindly do the necessary changes to get the PR in mergeable state.

2021-02-24 13:14 UTC, YashKumarVerma commented
check the latest commit in this branch: https://github.com/UniAuth/uniauth-backend/tree/list-user

2021-02-24 14:59 UTC, tanay13 commented
<img width="389" alt="loginuserpart" src="https://user-images.githubusercontent.com/61361310/109019231-d0a19600-76de-11eb-98e1-d59707c18d68.PNG">
@YashKumarVerma Please review, now its getting rendered properly

2021-02-24 17:34 UTC, YashKumarVerma requested changes
also do not include changes from the yarn.lock file.

Rest LGTM

2021-02-24 17:34 UTC, YashKumarVerma commented on src/application/application.controller.ts
> +  //   }
can we remove this if this is not required ?

2021-02-24 17:34 UTC, YashKumarVerma commented on src/application/application.service.ts
> +  async findUsers(id: string) {
change function name to `findUsersGrantedAccess()`

2021-02-24 17:34 UTC, YashKumarVerma commented on src/dashboard/dashboard.controller.ts
> +      });
render the error page here

2021-02-24 19:10 UTC, tanay13 commented
@YashKumarVerma I made the required changes, but I am not able to remove the yarn.lock from PR

2021-02-25 02:55 UTC, YashKumarVerma commented
@tanay13 https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request

2021-02-25 04:37 UTC, tanay13 commented
@YashKumarVerma Thanks for the link, I removed the file please check

2021-02-27 04:45 UTC, YashKumarVerma approved these changes

2021-02-27 04:53 UTC, merged

2021-02-27 04:53 UTC, YashKumarVerma commented
thanks !