Added Frontend part to display the names of user
UniAuth/uniauth-backend pull request #111
Opened 2021-02-22 11:07 UTC by MASTERCHIEF011

Fixes #106 
Fixes Frontend part.

2021-02-22 16:54 UTC, YashKumarVerma requested changes

2021-02-22 16:54 UTC, YashKumarVerma commented on views/dashboard/details.hbs
> +
no need to add util here

2021-02-22 16:54 UTC, YashKumarVerma commented on views/dashboard/dev.hbs
> +                        </form>
no need to create form, use simple anchor tag and take to new link

2021-02-22 17:00 UTC, MASTERCHIEF011 commented on views/dashboard/details.hbs
> +
OKAY

2021-02-22 17:04 UTC, MASTERCHIEF011 commented on views/dashboard/dev.hbs
> +                        </form>
But this link is sending the id of the app which i dont think can be achieved my an anchor tag

2021-02-23 03:35 UTC, YashKumarVerma commented
add screenshots of UI

2021-02-24 12:39 UTC, YashKumarVerma approved these changes

2021-02-24 12:40 UTC, merged

2021-02-24 12:41 UTC, YashKumarVerma commented
thanks !