status badges added in readme
UniAuth/uniauth-backend pull request #114
Opened 2021-02-23 08:34 UTC by kdsinghcoder

Fixed issue: #14

2021-02-24 19:06 UTC, YashKumarVerma requested changes

2021-02-24 19:06 UTC, YashKumarVerma commented on README.md
> +![Ensure Build](https://github.com/YashKumarVerma/authentico-backend/workflows/Ensure%20Build/badge.svg)
please use the batch from uniauth/uniauth-backend and not my personal account

2021-02-24 19:50 UTC, kdsinghcoder reviewed
Updated as per instructions

2021-02-25 02:45 UTC, YashKumarVerma commented
please get all the batches in a single line, immediately after the title. 
Also, change the title to `UniAuth Backend`
![image](https://user-images.githubusercontent.com/14032427/109095328-7f76be00-7741-11eb-91b2-77d9fafe4d76.png)

2021-02-25 04:04 UTC, YashKumarVerma commented
add
[![CodeFactor](https://www.codefactor.io/repository/github/uniauth/uniauth-backend/badge)](https://www.codefactor.io/repository/github/uniauth/uniauth-backend)

2021-02-26 09:44 UTC, kdsinghcoder reviewed
![image](https://user-images.githubusercontent.com/50829119/109283922-4f184800-7845-11eb-8c74-f76b86e49cb4.png)

2021-02-27 05:17 UTC, YashKumarVerma approved these changes

2021-02-27 05:19 UTC, merged

2021-02-27 05:19 UTC, YashKumarVerma commented
thanks !