customize application from single file
UniAuth/uniauth-backend pull request #130
Opened 2021-02-27 12:54 UTC by kdsinghcoder

# Issue Related to PR
- fixes #45 

# Checklist
- [x] Tests
- [x] Resolve Conflicts

# Screenshots
 ### After changing config file 
![image](https://user-images.githubusercontent.com/50829119/109387656-a80cdc80-7928-11eb-9260-2720c8caf3d4.png)
![image](https://user-images.githubusercontent.com/50829119/109387668-ce327c80-7928-11eb-8e0f-685db3714465.png)
![image](https://user-images.githubusercontent.com/50829119/109387677-dd192f00-7928-11eb-9f05-051ceec5911d.png)

#### etc

2021-02-27 19:58 UTC, YashKumarVerma requested changes

2021-02-27 19:58 UTC, YashKumarVerma commented on src/account/account.controller.ts
> +      return res.render('account/o/login', { app: applicationDetails, Cname: appData.Name });
what is cname?
can we use some easy to understand name here ?

2021-02-27 20:05 UTC, kdsinghcoder commented on src/account/account.controller.ts
> +      return res.render('account/o/login', { app: applicationDetails, Cname: appData.Name });
company name.
If its fine.

2021-02-27 20:11 UTC, YashKumarVerma requested changes

2021-02-27 20:11 UTC, YashKumarVerma commented on src/account/account.controller.ts
> +      return res.render('account/o/login', { app: applicationDetails, Cname: appData.Name });
no, please change.

2021-02-28 12:42 UTC, kdsinghcoder reviewed
Cname changes

2021-02-28 16:20 UTC, closed without merging