JS Error while creating new applicaiton  fix
UniAuth/uniauth-backend pull request #48
Opened 2021-02-11 17:41 UTC by kdsinghcoder

To fixing : #17

2021-02-11 21:06 UTC, YashKumarVerma requested changes

2021-02-11 21:06 UTC, YashKumarVerma commented on README.md
> +
empty lines not needed

2021-02-11 21:06 UTC, YashKumarVerma commented on src/user/user.schema.ts
> +export type UserDocument = User & Document;
i think we can undo this change.

2021-02-12 04:44 UTC, kdsinghcoder reviewed
Required changes are done.

2021-02-12 04:47 UTC, YashKumarVerma requested changes

2021-02-12 04:47 UTC, YashKumarVerma commented on src/user/user.schema.ts
> -
this line should not be removed.

earlier there was an extra space, only that had to be removed.

2021-02-13 06:08 UTC, kdsinghcoder reviewed
add again.

2021-02-13 06:21 UTC, YashKumarVerma approved these changes

2021-02-13 06:21 UTC, merged

2021-02-13 06:22 UTC, YashKumarVerma commented
Fixes #17