Update user profile
UniAuth/uniauth-backend pull request #50
Opened 2021-02-12 09:56 UTC by tanay13

solves #15 

@YashKumarVerma

2021-02-12 19:36 UTC, YashKumarVerma requested changes

2021-02-12 19:36 UTC, YashKumarVerma commented on src/user/user.controller.ts
> +
Send response only, no need to render.

2021-02-12 19:37 UTC, YashKumarVerma commented
@tanay13 ,

the reason that this does not render the profile page is that this is called via a network call.

i.e. the fetch command calls this, and this should only send data as a response. 

If you remove the `.json()` function from the fetch-promise-chain, then you will see that the server actually renders the page.

![image](https://user-images.githubusercontent.com/14032427/107814242-9d364180-6d97-11eb-9456-04831bd1c625.png)

## What you need to do
- either implement this feature as a simple form that responds to `POST` request on the same page.
- or, to avoid much changes in the current codebase, instead of redirecting the user, send a response (only json), and then show a message on the edit page.

2021-02-13 06:37 UTC, tanay13 commented on src/user/user.controller.ts
> +
Can you explain this a bit , I didn't get your point ?

2021-02-13 08:22 UTC, tanay13 commented
@YashKumarVerma Can you check once again? Instead of redirecting the user to profile page i redirected it to the dashboard . Now its working fine . Please review this .

2021-02-15 02:49 UTC, YashKumarVerma requested changes
![image](https://user-images.githubusercontent.com/14032427/107900227-682c1980-6f66-11eb-8d0f-2ae1825c9542.png)

but the edit page shows only the first component of the name

![image](https://user-images.githubusercontent.com/14032427/107900241-724e1800-6f66-11eb-8f52-d1d352279f0f.png)

2021-02-15 04:52 UTC, tanay13 commented
@YashKumarVerma please check i fixed it

2021-02-15 15:35 UTC, YashKumarVerma reviewed
Awesome Work !

2021-02-15 15:40 UTC, merged

2021-02-15 15:40 UTC, YashKumarVerma commented
Thanks a lot for your contributions!