Password restrictions not accepting valid password Fixed
UniAuth/uniauth-backend pull request #52
Opened 2021-02-14 13:11 UTC by kdsinghcoder

Fixed #51

2021-02-15 02:44 UTC, YashKumarVerma requested changes

2021-02-15 02:44 UTC, YashKumarVerma commented on views/account/register.hbs
> +                            pattern="^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$"
![image](https://user-images.githubusercontent.com/14032427/107899974-d3c1b700-6f65-11eb-80bb-2ac0f5da53cb.png)

Still not accepting this. "." is a special character.

2021-02-15 17:28 UTC, kdsinghcoder reviewed
fixed issue #52 

will now accept "." also

2021-02-16 04:56 UTC, YashKumarVerma requested changes
Too many changes / commits

2021-02-23 03:47 UTC, YashKumarVerma commented
Closing due to inactivity.

2021-02-23 03:47 UTC, closed without merging