Docker
UniAuth/uniauth-backend pull request #74
Opened 2021-02-16 09:09 UTC by kdsinghcoder

Fixed issue: #9

2021-02-16 18:33 UTC, YashKumarVerma requested changes
please add screenshots of docker image building

2021-02-19 04:39 UTC, kdsinghcoder reviewed
Updated docker file

2021-02-21 11:01 UTC, YashKumarVerma approved these changes

2021-02-21 11:15 UTC, merged

2021-02-21 11:16 UTC, YashKumarVerma commented
thanks !