Update user.controller.ts
UniAuth/uniauth-backend pull request #76
Opened 2021-02-16 12:57 UTC by fleventy-5

Hey I have commented all the module import in user.controller.ts except the service import. I'm new to open source so please tell me if i made some mistakes. Thanks

2021-02-16 18:36 UTC, YashKumarVerma requested changes

2021-02-16 18:36 UTC, YashKumarVerma commented on src/user/user.controller.ts
> +//import { AuthorizedUser } from './interface/user.interface';
these lines are not to be removed.

2021-02-17 13:17 UTC, fleventy-5 commented on src/user/user.controller.ts
> +//import { AuthorizedUser } from './interface/user.interface';
Ok sorry I thought I have to remove those modules too
So I have to remove only those methods for delete id or editing I'd etc?

2021-02-19 08:46 UTC, YashKumarVerma commented on src/user/user.controller.ts
> +//import { AuthorizedUser } from './interface/user.interface';
there are few functions (see issue body) that should be moved to dashboard service.

2021-02-19 09:34 UTC, closed without merging

2021-02-19 09:37 UTC, fleventy-5 commented
Hey @YashKumarVerma can you assign this to someone else I'm having trouble understanding the structure of typescript projects.
Sorry for wasting your time. Thanks

2021-02-19 09:38 UTC, fleventy-5 commented
I'll try looking for other issues that are easier.