Added delete application feature.
UniAuth/uniauth-backend pull request #99
Opened 2021-02-19 07:06 UTC by MASTERCHIEF011

Fixes #32

2021-02-19 08:39 UTC, YashKumarVerma commented
> Fixes #32

add changes done in this pr

2021-02-19 08:41 UTC, YashKumarVerma requested changes

2021-02-19 08:41 UTC, YashKumarVerma commented on src/application/application.service.ts
> +  async deleteApplication(id: String) {
no need to name it as "deleteApplication" as it is the service for application itself and it is being redundant.

2021-02-19 08:41 UTC, YashKumarVerma commented on src/dashboard/dashboard.controller.ts
> +  }
add validation to check if admin is sending a request to delete.

2021-02-19 08:47 UTC, MASTERCHIEF011 commented on src/dashboard/dashboard.controller.ts
> +  }
okk

2021-02-19 12:29 UTC, YashKumarVerma requested changes

2021-02-19 12:29 UTC, YashKumarVerma commented on src/application/application.service.ts
> +
the logic to test whether user is authorized or not to delete an application must reside in the controller

2021-02-19 12:41 UTC, MASTERCHIEF011 commented on src/application/application.service.ts
> +
okay

2021-02-19 17:54 UTC, YashKumarVerma reviewed
Rest LGTM

2021-02-19 17:54 UTC, YashKumarVerma commented on src/application/application.service.ts
> +  async delete(id: String) {
the id is of type ObjectId

2021-02-19 17:54 UTC, YashKumarVerma commented on src/dashboard/dashboard.controller.ts
> +    if (JSON.stringify(user.admin) === JSON.stringify(loggedInUser.id)) {
could you explain what is the meaning of 
```js
if (JSON.stringify(user.admin) === JSON.stringify(loggedInUser.id)) {
```

2021-02-19 18:23 UTC, MASTERCHIEF011 commented on src/dashboard/dashboard.controller.ts
> +    if (JSON.stringify(user.admin) === JSON.stringify(loggedInUser.id)) {
one was of type objectId and the other was of type String so to make their types equal i converted them into a Json String.

2021-02-19 18:38 UTC, MASTERCHIEF011 commented on src/dashboard/dashboard.controller.ts
> +    if (JSON.stringify(user.admin) === JSON.stringify(loggedInUser.id)) {
Here I am checking whether the current user i.e (loggedInUser.id) who is giving the delete command is same as the one who created it i.e (user.admin).

2021-02-19 20:03 UTC, YashKumarVerma commented on src/dashboard/dashboard.controller.ts
> +    if (JSON.stringify(user.admin) === JSON.stringify(loggedInUser.id)) {
could you check the datatype of `user.admin` ?

2021-02-20 05:32 UTC, MASTERCHIEF011 commented on src/dashboard/dashboard.controller.ts
> +    if (JSON.stringify(user.admin) === JSON.stringify(loggedInUser.id)) {
Upon executing the below command 
![image](https://user-images.githubusercontent.com/54094722/108584893-df005280-736a-11eb-9d28-5368cc6ed71a.png)

I get this as a result:
![image](https://user-images.githubusercontent.com/54094722/108584916-0c4d0080-736b-11eb-8b39-afad9f3b07bd.png)
So i guess that user.admin is of object type.

2021-02-21 10:53 UTC, YashKumarVerma approved these changes

2021-02-21 10:59 UTC, YashKumarVerma approved these changes

2021-02-21 11:00 UTC, merged

2021-02-21 11:00 UTC, YashKumarVerma commented
thanks !